# Generated by Django 3.2.4 on 2021-07-12 20:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('mensagem', models.CharField(max_length=200)),
                ('visto', models.CharField(max_length=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('nipc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('morada', models.CharField(max_length=150)),
                ('n_porta', models.CharField(max_length=10)),
                ('cod_postal', models.CharField(max_length=8)),
                ('localidade', models.CharField(max_length=20)),
                ('concelho', models.CharField(max_length=20)),
                ('telefone', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GastosProd',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('percentagem', models.FloatField()),
            ],
            options={
                'db_table': 'gastos_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrucoes',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('instrucao', models.BinaryField()),
                ('imagem', models.BinaryField()),
            ],
            options={
                'db_table': 'instrucoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('quantidade', models.FloatField()),
                ('especificacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cor', models.CharField(max_length=20)),
                ('alerta_qt_minima', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MpProd',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
            ],
            options={
                'db_table': 'mp_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdVendido',
            fields=[
                ('codigo_venda', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=10)),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'prod_vendido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.BinaryField()),
                ('custo_producao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lucro', models.FloatField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'tipo_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidMedida',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'unid_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artesao',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, verbose_name='email address')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'artesao',
                'managed': True,
                'unique_together': {('email', 'username')},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecimento',
            fields=[
                ('materia_prima_codigo', models.OneToOneField(db_column='materia_prima_codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artgest.materiaprima')),
            ],
            options={
                'db_table': 'fornecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstProd',
            fields=[
                ('tipo_prod_codigo', models.OneToOneField(db_column='tipo_prod_codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artgest.tipoprod')),
            ],
            options={
                'db_table': 'inst_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('artesao_codigo', models.OneToOneField(db_column='artesao_codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artgest.artesao')),
                ('tempo_producao', models.IntegerField()),
                ('custo_hora_producao', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'producao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoStock',
            fields=[
                ('tipo_prod_codigo', models.OneToOneField(db_column='tipo_prod_codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artgest.tipoprod')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'produto_stock',
                'managed': False,
            },
        ),
    ]
