# Generated by Django 3.2.4 on 2021-07-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastosprod',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mpprod',
            options={'managed': True},
        ),
    ]
