# Generated by Django 3.2.4 on 2021-07-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0002_auto_20210712_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artesao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gastosprod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mpprod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoprod',
            options={'managed': True},
        ),
    ]
