# Generated by Django 3.2.4 on 2021-07-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0003_auto_20210712_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprod',
            options={'managed': False},
        ),
    ]
