# Generated by Django 3.2.4 on 2021-07-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0004_alter_tipoprod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrucoes',
            options={'managed': True},
        ),
    ]
