# Generated by Django 3.2.4 on 2021-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0005_alter_instrucoes_options'),
    ]

    operations = [
    ]
