# Generated by Django 3.2.4 on 2021-07-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0006_auto_20210715_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrucoes',
            options={'managed': False},
        ),
    ]
