# Generated by Django 3.2.4 on 2021-07-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0008_alter_producao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'managed': False},
        ),
    ]
