# Generated by Django 3.2.4 on 2021-07-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0009_alter_producao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'managed': True},
        ),
    ]
