# Generated by Django 3.2.4 on 2021-07-15 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0010_alter_producao_options'),
    ]

    operations = [
    ]
