# Generated by Django 3.2.4 on 2021-07-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgest', '0011_auto_20210715_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'managed': False},
        ),
    ]
